### ISSUE TITLE
visualization of scannet

### ISSUE THREAD

**Issue by meteorshowers** [viscom-ulm/MCCNN#1]
Hi 
Thanks for your great work.
Could you tell me how do you visualize the result of scannet?
Your figure is very pretty!
Thanks a lot!

**Comment by phermosilla** [comment]
Hello! 
Thank you for the interest. 
Regarding your question, the script _ScanNetEval.py_ evaluates the test dataset. If you run the script with the parameter _--saveModels_, the script will save the point clouds with color in a folder with the name _savedModels_.  
Then, in the folder _utils_, there is another script called _GenerateSphereMeshes.py_, which process all the saved models in a certain folder and creates a ply file containing a 3D scene for each of them. In these scenes, each point is represented by a colored sphere. Since the ScanNet models have a lot of points, is better if you execute the script with _--sphSub 0_ (this parameter determines the subdivision of the spheres). Also, I recommend to do not apply this script to the whole test dataset, since the size of the output ply files can be quite big.
Lastly, I used these ply models in Blender with cycles renderer to generate the final images.
I hope this is helpful for your work.
Best

**Comment by meteorshowers** [comment]
@phermosilla 
Thanks a lot, I will try it!
