### ISSUE TITLE
Train one model for both ShapeNet and ScanNet

### ISSUE THREAD

**Issue by chenzhutian** [viscom-ulm/MCCNN#2]
Thanks for such a great work and tidy repo!
Do you train different models seperately for ShapeNet and ScanNet?
Can we train one model to finish the segmentation task on both ShapeNet and ScanNet?

**Comment by phermosilla** [comment]
Thanks for your interest in our project. Regarding your question, yes, we train two models, one for ShapeNet and another one for ScanNet. Training one model for both tasks can be done but it is more challenging since the tasks and the datasets are very different. If you meant by model, network architecture, you can create a network architecture for both tasks modifying the radii of the convolutions properly, but we decided to use a different one.

**Comment by chenzhutian** [comment]
Oh I see. But are both ScanNet and ShapeNet for segmentation task?

**Comment by phermosilla** [comment]
The tasks are similar but the dataset is not. In ShapeNet you have a single object sampled with at most 3000 points. In ScanNet you have rooms sampled with a maximum of 600.000 points. Other approaches subdivided the scene in small chunks of 8000 so they are able to use a similar architecture for both tasks. However, we process the rooms all at once, then we need a deeper architecture. Soon we will release the code to train a network using chunks.

**Comment by chenzhutian** [comment]
Got it!
Thanks for your kindly reply.
