### ISSUE TITLE
questions about the code

### ISSUE THREAD

**Issue by eternal-heart** [viscom-ulm/MCCNN#7]
Hello,I‘m a student and i'm interested in your research.’I have some questions about your code,such as the code "pointIndex =currentIndex*3"  in the "sort_gpu.cu" , why the currentIndex to be multiplied by 3?
 And in the later,while compute the "maxAabbSize",why the currentIndex to be multiplied by 3 and plus 1 or 2?

**Comment by phermosilla** [comment]
Hello, thanks for your interest in our code. These multiplications by 3 are because we are passing an array of floats to the kernel which represents 3D points. Since each point is composed of 3 float values, in order to access the appropriate point we have to multiply by 3 the point index. Moreover, the summations of +1 and +2 are there to access the y and z components by displacing the pointer one or two positions along the vector.

**Comment by eternal-heart** [comment]
Thanks for your reply.And can you explain the prosess of "propagate_offsets"? I can't uderstand the use of "OFFSET_BLOCK_SIZE" and the principle of the computation of offsets.

**Comment by phermosilla** [comment]
This file implements the sorting of points based on the cell id inside a regular grid. This is used later to fast access the neighboring points of each point. To do that in the GPU, I used a similar implementation of the Radix sort algorithm to the one described here:

https://on-demand.gputechconf.com/gtc/2014/presentations/S4117-fast-fixed-radius-nearest-neighbor-gpu.pdf

This algorithm uses a scan algorithm to propagate the counters for each cell id. This scan algorithm is implemented in the function propagate_offsets. The algorithm used is similar to the one described here: 

https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-39-parallel-prefix-sum-scan-cuda
